// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Addr struct {
	_tab flatbuffers.Table
}

func GetRootAsAddr(buf []byte, offset flatbuffers.UOffsetT) *Addr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Addr{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Addr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Addr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Addr) Ip(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Addr) IpLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Addr) MutateIp(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Addr) Port() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Addr) MutatePort(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func AddrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AddrAddIp(builder *flatbuffers.Builder, ip flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ip), 0)
}
func AddrStartIpVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AddrAddPort(builder *flatbuffers.Builder, port int32) {
	builder.PrependInt32Slot(1, port, 0)
}
func AddrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
