// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package request

import "strconv"

type AllRequests byte

const (
	AllRequestsNONE                AllRequests = 0
	AllRequestsRegistrationRequest AllRequests = 1
	AllRequestsConnectionRequest   AllRequests = 2
)

var EnumNamesAllRequests = map[AllRequests]string{
	AllRequestsNONE:                "NONE",
	AllRequestsRegistrationRequest: "RegistrationRequest",
	AllRequestsConnectionRequest:   "ConnectionRequest",
}

var EnumValuesAllRequests = map[string]AllRequests{
	"NONE":                AllRequestsNONE,
	"RegistrationRequest": AllRequestsRegistrationRequest,
	"ConnectionRequest":   AllRequestsConnectionRequest,
}

func (v AllRequests) String() string {
	if s, ok := EnumNamesAllRequests[v]; ok {
		return s
	}
	return "AllRequests(" + strconv.FormatInt(int64(v), 10) + ")"
}
