// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package request

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RegistrationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRegistrationRequest(buf []byte, offset flatbuffers.UOffsetT) *RegistrationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RegistrationRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RegistrationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RegistrationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RegistrationRequest) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RegistrationRequest) LocalAddr(obj *Addr) *Addr {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Addr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RegistrationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RegistrationRequestAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func RegistrationRequestAddLocalAddr(builder *flatbuffers.Builder, localAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(localAddr), 0)
}
func RegistrationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
