// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package request

import "strconv"

type RequestType int8

const (
	RequestTypeRegistration RequestType = 0
	RequestTypeConnection   RequestType = 1
)

var EnumNamesRequestType = map[RequestType]string{
	RequestTypeRegistration: "Registration",
	RequestTypeConnection:   "Connection",
}

var EnumValuesRequestType = map[string]RequestType{
	"Registration": RequestTypeRegistration,
	"Connection":   RequestTypeConnection,
}

func (v RequestType) String() string {
	if s, ok := EnumNamesRequestType[v]; ok {
		return s
	}
	return "RequestType(" + strconv.FormatInt(int64(v), 10) + ")"
}
