// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Peer struct {
	_tab flatbuffers.Table
}

func GetRootAsPeer(buf []byte, offset flatbuffers.UOffsetT) *Peer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Peer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Peer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Peer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Peer) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Peer) LocalAddr(obj *Addr) *Addr {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Addr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Peer) RemoteAddr(obj *Addr) *Addr {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Addr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PeerStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PeerAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func PeerAddLocalAddr(builder *flatbuffers.Builder, localAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(localAddr), 0)
}
func PeerAddRemoteAddr(builder *flatbuffers.Builder, remoteAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(remoteAddr), 0)
}
func PeerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
